#!/bin/sh
#
# Custom dwm startup script.
#
# Author: Dimitris Gerasimou <https://github.com/dimgerasimou>
#

# Start picom
/usr/bin/picom -b

# Start dwmblocks
/usr/local/bin/dwmblocks &

# Keyboard layouts
setxkbmap -layout us,gr -option grp:win_space_toggle

# Multi monitor setup
(sleep 0.2 && (xrandr --output HDMI-0 --rate 75 --left-of eDP-1-1 --output eDP-1-1 --primary --rate 144)) &

# Start easyeffects for equalizer
(sleep 0.5 && (nohup easyeffects --gapplication-service &)) &

# Set Wallpaper
(sleep 0.2 && (feh --bg-fill $HOME/Pictures/Background.png)) &

# Set default volume settings
(sleep 0.2 && (/usr/bin/wpctl set-volume @DEFAULT_AUDIO_SINK@ 0.8)) &
(sleep 0.2 && (/usr/bin/wpctl set-mute @DEFAULT_AUDIO_SOURCE@ 1)) &
(sleep 0.6 && (pkill -RTMIN+10 dwmblocks))&

# Start mate polkit agent
/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 &

# Start dunst
/sur/bin/dunst &

# Start dwm
/usr/local/bin/dwm
