#!/bin/sh
#
# Custom dwm startup script.
#
# Author: Dimitris Gerasimou <dimgerasimou@gmail.com> http://github.com/dimgerasimou
#

# Set Wallpaper
feh --bg-fill /home/dimgerasimou/Pictures/Wallpapers/star_destroyer.jpg

# Start tray applets
#/usr/bin/optimus-manager-qt &

# Start dwmblocks
/usr/local/bin/dwmblocks &

# Start dwm
/usr/local/bin/dwm
